### ISSUE TITLE
Diseño de la app

### ISSUE THREAD

**Issue by omiras** [PIMEC-2023/crazytiles#1]
## Objetivos

1. Hacer un diseño simple de la app en Figma
2. Establecer los colores primarios, secundarios, etc de toda la app en el fichero assets/base.css
3. Triar una serie de icones o imatges per a les cartes

**Comment by omiras** [comment]
@mariaarandam @gegebe Cuando tengáis el enlace del figma, compartidlo por favor.

**Comment by omiras** [comment]
- El logo que va compartir Maria
- Nom:
   1. CrazyTiles 
   2. crazyTiles
   3. Crazy-Tiles

**Comment by omiras** [comment]
![Image](https://github.com/PIMEC-2023/crazytiles/assets/3286458/5a6c6a99-ac8f-45f6-a460-c50fbd4cfe9f)

**Comment by omiras** [comment]
1. En components cread un componente llamado DesignGuides.vue
2. Importar en componente en App.vue
3. Importar un asset para mostrar a los compis como se hace, por ejemplo, el del reverso de la carta
4. Cread un texto donde apliqueis los colores elegidos  principales para la app (quizás dos párrafos)

**Comment by gegebe** [comment]
Añadidas las frutas que María ha creado en Figma, pusheado y pull request.

**Comment by gegebe** [comment]
Simplificación del apartado configuración, añadida captura de pantalla a la issue #8
