### ISSUE TITLE
Añadir sonidos

### ISSUE THREAD

**Issue by omiras** [PIMEC-2023/crazytiles#10]
# Análisis

Queremos que en nuestra app reproduzca sonidos discretos cada vez que se acierte o se falle una carta
También al finalizar el juego

Buscar en varias Web sonidos gratuitos sin copyright para usar en nuestra app. Da un poco igual el formato, normalmente es .wav, .mp3

Cuando tengáis los sonidos implementados, pasad a poder configurar el muteo/desmuteo
Fijaos en diseño que tienen dos iconos para mutear/desmutear los sonidos.

**Comment by OriolB-Uri** [comment]
Posible sonido: https://pixabay.com/es/sound-effects/success-bell-6776/

**Comment by GalisGalisteo** [comment]
Mis propuestas:

[Musica fondo](https://freesound.org/people/Seth_Makes_Sounds/sounds/685334/)
[Sonido girar carta](https://freesound.org/people/sonically_sound/sounds/624880/)
[Sonido acierto](https://freesound.org/people/EVRetro/sounds/501103/)

Todo muy game boy 80'! jajaja!

**Comment by omiras** [comment]
- NO teneis vosotros que aplicar diseño. Centraos en los sonidos. 
- Podeis crear una función que se encargue de reproducir un sonido que le viene por parámetro

```
// Execute this function to play the audio
function playPokemonMp3() {
  var audio = new Audio("whos-that-pokemon_.mp3");

  audio.play();
}
```

**Comment by omiras** [comment]
@GalisGalisteo Me gusta mucho la música de fondo 👯

**Comment by omiras** [comment]
Debemos cambiar la variable de estado que controla si hay sonido o no por una _prop_
