### ISSUE TITLE
Pantalla de fin de juego

### ISSUE THREAD

**Issue by omiras** [PIMEC-2023/crazytiles#16]
# Objetivos

Fijaos en el diseño de [figma](https://www.figma.com/proto/dJULKPVEZujNOPI1Gxnz8a/crazyTiles-by-macedonia---memory?type=design&node-id=109-2763&t=PVbixj7a8n5I8gWw-0&scaling=min-zoom&page-id=4%3A2&starting-point-node-id=45%3A28&show-proto-sidebar=1)

1. Crear la pantalla de fin de juego (victoria)
2. Crear una página nueva en src/pages/VictoryPage.vue
3. Añadir en store.js está página (pedid ayuda a @omiras )
4. Maquetad tal cual el diseño que nos proporcionan la página
5. Modificar src/components/GameBoard.vue para que cuando el jugador acierte todas las parejas, navegar a la página de victoria con la función **changePage**
6. Dejad un texto de intentos y tiempo tal cual como aparece en el diseño , que lo cambiaremos más tarde
7. Los botones   
    1. Reiniciar - > simplemente teneis que volver a la página del jeugo con la función changePage
    2. Nou Joc -> teneis que ir a la página de inicio

**Comment by omiras** [comment]
Hola,

Ya podéis acceder al diseño de figma en https://www.figma.com/file/dJULKPVEZujNOPI1Gxnz8a/crazyTiles-by-macedonia---memory?node-id=77%3A241&mode=dev

Quizás de momento lo hacemos sin las serpentintas? Lo comentamos el lunes cómo queremos hacer esto. Sería lo suyo incluir algunos assets y que hubiera una animación de serpentinas "cayendo" !

**Comment by omiras** [comment]
Podéis exportar los assets del figma directamente: 

![Image](https://github.com/PIMEC-2023/crazytiles/assets/3286458/1ddf49c8-4119-447a-8e3d-8ae2c428c377)

Empezad por uno solo!  (una estrellita y usarla varias veces). Y luego ya vemos

**Comment by mariaarandam** [comment]
Adjunt tots els elements de confetti

[Confetti-crazyTiles by macedonia - memory.zip](https://github.com/PIMEC-2023/crazytiles/files/13472381/Confetti-crazyTiles.by.macedonia.-.memory.zip)
