### ISSUE TITLE
Juego base

### ISSUE THREAD

**Issue by omiras** [PIMEC-2023/crazytiles#2]
## Objetivo

Juego base. Poder mostrar un conjunto de cartas (divs sin estilo) y poder ir haciendo parejas

## Pasos a seguir

0. Botón para empezar juego
1. Distribuir un conjunto de cartas una lado de la otra , con cierta formato de cuadricula
2. El usario hace clic en una de las cartas. Se muestra su reverso
3. El usuario hace clic en otra de las cartas. Se muestra su reverso
4. Si los número/imagen coinciden, desaparecen las cartas (se hacen invisibles)
5. Si no coinciden, pues las dos cartas vuelven a su anverso
6. Cuando se han acertado todas las cartas, mostrar un mensaje de victoria y dar la posiblidad de reiniciar el juego

Estilos: los mínimos. Lo más importante es que sean las cartas en formato de cuadricula. (display: grid).

**Comment by omiras** [comment]
Recomiendo la manera general de afrontar estos problemas en Vue

1. Pensar en la estructura más simple para albergar las cartas. 
2. Primero mostrar todas las cartas en cuadrícula de forma estática, es decir, si con la estructura de datos elegida sois capaces de generar tantas cartas como necesitéis.
3. Pensad cual es el estado de la aplicación. Hilar las variables de estado con el <template>
5. Cambiar las variables de estado y ver si reaccionan las cartas como esperais (manualmente o en las herramientas de desarrollo del navegador de Vue)
6. Finalmente, codificar los eventos (click) en las cartas que se encarguen de cambiar las variables de estado adecuadas.
7.

**Comment by omiras** [comment]
Tenemos que tener en cuenta de que no deberíamos poder hacer click en cartas que ya son correctas (emparejadas)

**Comment by GalisGalisteo** [comment]
He creado la rama _galis-juego-base_ con:

- Función board por si finalmente se decide que el usuario elija el tamaño del tablero (X , Y)
- En función checkCards: 
    · Implementación firstClick sin basarse en el firstSelectedCard.value
    · setTimeout 1s para resetear firstSelectedCard.value y secondSelectedCard.value
    · Añado comprobación end game y reseteo match.value
- Función disappearCard para que la carta desaparezca cuando se acierta con una transición de 1s
- Cambio v-if por v-show en el <span>
- Aplico estilo grid y centro
- Añado clase tile al button
- Doy el tamaño al article en vez de al button.tile y este lo pongo a 100% tanto width como height
- He probado poner una imagen del fondo al tile y funciona! :)

**Comment by omiras** [comment]
Comprobar si realmente al aplicar un v-show en una de las cartas, conserva el espacio si está en grid.
si no funciona, tirad por el :disabled .

**Comment by omiras** [comment]
BUG; Si pulsamos dos veces sobre el mismo número, también desaparece el otro número que es igual
