### ISSUE TITLE
Imágenes personalizadas + Local storage

### ISSUE THREAD

**Issue by GalisGalisteo** [PIMEC-2023/crazytiles#29]
Intentar implementar LocalStorage con el composable [vue-composable](https://pikax.me/vue-composable/composable/storage/localStorage.html).

**Comment by omiras** [comment]
@GalisGalisteo en general funciona muy bien! Lo único es lo que te muestro en el vídeo:

https://oscarm.tinytake.com/msc/OTAwMTIyN18yMjQ4MjM5OA

Creo que eso ocurre porque "compeltas" el array de imágenes antes de iniciar el juego. Entonces claro, cuando volvemos a la pantalla de configuración, se ve el array completado con las frutas. El problema es que esto pasa incluso si no pones imágenes persnalizadas, y simplemente elegimos la opcion "personalizar"

Como solución se me ocurre:

1. Separar el array de imágenes personalizadas e imágenes predefinidas en **src/store.js**
2. Usar dicha variable para ir almacenando las imágenes que sube el usuario
3. Solo cuando el usuario hace clic en "Guardar configuració", entonces tenemos que generar el array final de imágenes y guardarlo en store.gameConfig.urlsArray

**Comment by GalisGalisteo** [comment]
- He puesto las importaciones y el array de fotos en el store.js porque he pensado que como siempre es el mismo mejor ahí

- He quitado del gameConfig el fruitsArray porque lo paso directamente en el GameBoard

- He añadido en el GameBoard una computed para saber si enviar el array de frutas o de imágenes subidas a la prop _urls-array_del GameBoard

- He cambiado el nombre de la variable urlsArray por uploadedImgs

- He añadido mensaje  "Et falten per pujar..."

- Icono upload photos integrado con el Widget
