### ISSUE TITLE
Cambiar type file por imagen

### ISSUE THREAD

**Issue by gegebe** [PIMEC-2023/crazytiles#34]
- Cambiar la estética del botón examinar por un icono.

**Comment by omiras** [comment]
@gegebe Recuerda que se puede crear la rama de desarrollo des de aqui mismo :)

![image](https://github.com/PIMEC-2023/crazytiles/assets/3286458/96689ea7-d124-4142-8eb0-c652e1b46f33)

**Comment by gegebe** [comment]
Me vas matar porque no veo como hacerlo y lo hicimos en clase : $$



![Image](https://github.com/PIMEC-2023/crazytiles/assets/1293092/7d82df5b-c03f-485b-83a4-39f7aaee0520)

**Comment by omiras** [comment]
No lo pone fácil GotHub. Lo que ocurre es que solo se ve el enlace si vas desde Issues 

https://github.com/PIMEC-2023/crazytiles/issues/34
