### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by omiras** [PIMEC-2023/crazytiles#4]
## Objetivo

Crear una lading page estilo

1. https://singulars2022.github.io/cinedebarrio-landingpage/
2. https://animalslist-19bbf.web.app/
3. https://donapp-sand.vercel.app/

No hacer la landing page de 0. Buscad plantillas que sean fáciles de adaptar y usarla en nuestro proyecto. 
¿Dónde puedo encontrar plantillas?

[1. Html5 up](https://html5up.net/)
[2. Bootstrap](https://startbootstrap.com/landing-pages)
[3. W3.CSS](https://www.w3schools.com/w3css/w3css_templates.asp)

Vamos a hacer algo simple, algo como el primer ejemplo de la primera lista.
La landing deberá incluir

1. Algunos pantallazos del juego (aun no lo tenemos)
2. Una breve descripción de qué va el proyecto y un botón para ir a la URL de la app (todavía no tenemos)
3. Una sección de equipo, parecida a la de los ejemplos de la primera lista

## Pasos a seguir

1. Clonar el repo https://github.com/PIMEC-2023/landing-page
2. Buscar una plantilla que os guste y adaptarla
3. Subir los cambios

**Comment by omiras** [comment]
A todas las personas, vamos a necesitas de cada uno:

1. URL de vuestro GitHub
2. URL de vuestro Linkedin
3. Una foto vuestro o la imagen que queráis usar en su lugar.

Ponedlo en esta misma issue como un comentario

**Comment by GalisGalisteo** [comment]
GitHub: https://github.com/GalisGalisteo
Linkedin: https://www.linkedin.com/in/jordigalisteomendoza
![foto-galis](https://github.com/PIMEC-2023/crazytiles/assets/83426851/4d8dd3e8-7f4f-471d-b463-270d4c85a2b4)

**Comment by gegebe** [comment]
LinkedIn: https://www.linkedin.com/in/gegebe/
GitHub: https://github.com/gegebe
Adjunto imagen, un poco chunga, pero por lo menos tenéis material 
![Gerard-Girbes-Berges](https://github.com/PIMEC-2023/crazytiles/assets/1293092/44dd1cb1-82c2-4699-a8aa-5a55f24f010b)

**Comment by Albertina75** [comment]
![miyodelfuturo](https://github.com/PIMEC-2023/crazytiles/assets/145276835/0c834b51-79a2-403b-9603-1379fff2b8de)

**Comment by Albertina75** [comment]
https://www.linkedin.com/in/albertina-esteves-garcia/

**Comment by Albertina75** [comment]
https://github.com/Albertina75 jajajjaa

**Comment by Ester-0** [comment]
LinkedIn: https: https://es.linkedin.com/in/ester-fenero-carmona/
GitHub: https://github.com/Ester-0
![20230709_135934](https://github.com/PIMEC-2023/crazytiles/assets/145297563/8add82b8-0ff0-4a45-b42c-cad10b0af786)

**Comment by KateOs99** [comment]
![photo_2023-11-21 12 15 16 (1)](https://github.com/PIMEC-2023/crazytiles/assets/145285465/822f177d-22c7-4ffe-aee5-2dc717a1111b)

**Comment by KateOs99** [comment]
Sólo tengo GitHub: https://github.com/KateOs99

**Comment by omiras** [comment]
1. Por CSS, teneis que hacer más pequeña la foto o el modal
2. En el apartado RRSS , poner el icono de GitHub con el enlace al repositorio y dejar la de Linkedin. 
3. Cercioraos que los dos colores principales de vuestra landing page sean los mismos que los principales del juego @gegebe @mariaarandam Cuando tengais los colores definitivos comunicadlo a landing page por favor.
4. Dejamos de momento las fotos grandes y alargas. Como trabajo futuro, hay que solventar la deformidad (pero si lo conseguís solventar hoy pues bien)
5. En carousel irán las diferentes pantallas de la app con unas pequeñas directrices de como configurar y jugar

**Comment by gegebe** [comment]
Verde: #02C4AC
Azul: #1239b9

**Comment by omiras** [comment]
![Image](https://github.com/PIMEC-2023/crazytiles/assets/3286458/6c97fc3a-15e1-4f13-af92-8c41abff38d7)

GitHub: https://github.com/omiras
Linkedin: https://www.linkedin.com/in/mirasortiz/

**Comment by DMucci** [comment]
https://www.linkedin.com/in/diego-mucci-4b278a159/
https://github.com/DMucci



![Image](https://github.com/PIMEC-2023/crazytiles/assets/145248570/d79a16eb-367f-4376-8860-00238bba7a70)

**Comment by Ester-0** [comment]
FALTA: subir fotos pendientes, arreglar tamaño fotos, quitar el automático del carousel y poner los iconos más oscuros, poner el logotipo donde pone macedonia

**Comment by mariaarandam** [comment]
Hola.
Més material;
LinkedIn: [https://www.linkedin.com/in/mariaarandamonso/](url)
GitHub: [https://github.com/mariaarandam](url)



![Image](https://github.com/PIMEC-2023/crazytiles/assets/145118086/28305366-7d66-4fe3-8e5b-9b3d7b57a46f)

**Comment by omiras** [comment]
Queda por hacer:

1. Valorar si cambiar el logo a la izquierda
2. Cambiar la URL del footer de GitHub que vaya al repo crazytiles
3. @gegebe @mariaarandam Podéis en algún momento acabar de aplicar los colores donde creáis que deben ir? (clonar y vosotros mismos modiicar el repo)
4. Cuando tengamos la app preparada, hacemos los pantallazos y los cambiamos en el carousel

**Comment by mariaarandam** [comment]
Per si afegim els credits a la landing page, serien;
- Logo fruites; <a href="https://www.flaticon.es/iconos-gratis/ensalada-de-frutas" title="ensalada de frutas iconos">Ensalada de frutas iconos creados por Freepik - Flaticon</a>
- Icones fruites; Image by Freepik
